### PR TITLE
Add new Flatpak logging support

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Add support for https://github.com/obsproject/obs-studio/pull/8212 which replace `Distribution:` on Flatpak.

### Motivation and Context

Keep the Wayland check working.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
If you can provide logs before and after the OBS Studio PR change, someone else can test them.

**Comment by tytan652** [comment]
Log used in #81 to trigger XWayland warning: https://obsproject.com/logs/eKb1Q19JR-Hq82Jd

X11 Flatpak log: https://obsproject.com/logs/Gx175Fg7eJLVxelC
XWayland Flatpak log: (need to relog under Wayland so soon)

**Comment by RytoEX** [comment]
Could you clarify which logs should generate which warnings? Only the first log generates a Critical warning for me, but not the Critical warning in this PR.
image

The other three logs just have an Info item about a custom OBS version.

**Comment by tytan652** [comment]
This PR just allows the XWayland Flatpak log to trigger the XWayland warning with the logging changes (even if a XWayland scenario has low chance to happen).

Because without the PR, it does not show the warning.

**Comment by tytan652** [comment]
The ones maks with XWayland throw the warning.

**Review by RytoEX — APPROVED** [review]
Discussed off-thread and further tested against a log with Wayland on Ubuntu 20.04. Looks good to me.

**Pull request merged**
