### PR TITLE
Update NVIDIA driver website URL

### PR DESCRIPTION
**Pull request by prgmitchell**
### Description

This updates the NVIDIA driver website URL to the .com URL instead of .de.

### Motivation and Context

Saw the German site was being used.

### How Has This Been Tested?

Website loads.

### Types of changes

- Tweak (non-breaking change to improve existing functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
I must admit, being on a small screen, I was very confused with the new site because there is no obvious indication that a search has completed.

**Comment by prgmitchell** [comment]
@RytoEX I just checked on my phone and didn't think it was necessarily worse than the other site in this regard. I should also point out that on some model GPU's, I've seen the current site not actually list the most updated driver. I can maybe try to find an example but this has come up in support a few times.

**Comment by prgmitchell** [comment]
I do also want to point of that the current link directs to the German NVIDIA website.

**Comment by RytoEX** [comment]
> I do also want to point of that the current link directs to the German NVIDIA website.

Sure, though that could be fixed by simply replacing nvidia.de with nvidia.com.

The old site is obvious that results have been returned, as it redirects you to a driver download page.
image

The new site loads a spinner, but replaces the spinner with the same search form, with no good visual indication that there are search results below.
image

I won't block this change if some folks who regularly handle support think this is the better option, but it's not obviously better to me.

**Comment by RytoEX** [comment]
> If I go to nvidia.com and click on "Drivers" it takes me to https://www.nvidia.com/Download/index.aspx?lang=en-us and I'd rather use that because I've found the GeForce/gaming specific page confusing. Took me a bit to even see the list of drivers it supposedly loaded after the spinner disappeared.

This was exactly my experience. The scrollbar is themed with such low contrast between elements that I didn't realize the page had resized.

**Comment by prgmitchell** [comment]
PR has been updated with the link Rodney provided.

**Comment by RytoEX** [comment]
> PR has been updated with the link Rodney provided.

> https://www.nvidia.com/Download/index.aspx?lang=en-us

Doesn't this hardcode the page the user loads to English (US)? Does dropping the `?lang=en-us` part make the site attempt to load a locale specific page?

**Pull request merged**
