### PR TITLE
plugins: Update plugins list for obs-webrtc, obs-qsv11, and coreaudio-encoder

### PR DESCRIPTION
**Pull request by prgmitchell**
### Description

This updates the plugins list to exclude from the third-party plugins detection. With this change, obs-webrtc is now included in the common plugins, obs-qsv11 has been added to the Linux plugins, and coreaudio-encoder has been moved from the common plugins to the Windows and Mac plugins.

### Motivation and Context

obs-webrtc is now being shipped with with OBS on all platforms, obs-qsv11 has been added to Linux builds, and it was pointed out the coreaudio-encoder is not available on Linux.

### How Has This Been Tested?

Tested a log with obs-webrtc installed, it no longer shows as a third party plugin: https://obsproject.com/logs/TCpUxI4EUKztOZuj
Didn't have a Linux log to test but I can't think of any potential issues here.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by norihiro** [comment]
Probably `obs-qsv11` can be listed in `commonPlugins`.
`coreaudio-encoder` is listed in `commonPlugins` though it's not supported on Linux.

**Comment by prgmitchell** [comment]
> Probably `obs-qsv11` can be listed in `commonPlugins`. `coreaudio-encoder` is listed in `commonPlugins` though it's not supported on Linux.

Is this the only inconsistency? I'd rather move `coreaudio-encoder` out of the `commonPlugins` list and into the Windows/Mac plugins list if that is the case.

**Comment by RytoEX** [comment]
> > Probably `obs-qsv11` can be listed in `commonPlugins`. `coreaudio-encoder` is listed in `commonPlugins` though it's not supported on Linux.
> 
> Is this the only inconsistency? I'd rather move `coreaudio-encoder` out of the `commonPlugins` list and into the Windows/Mac plugins list if that is the case.

obs-qsv11 isn't available on macOS, so it should not be in commonPlugins. The coreaudio-encoder change request is valid.

**Comment by prgmitchell** [comment]
I have updated the PR to include moving coreaudio-encoder out of the common plugins list.

**Comment by RytoEX** [comment]
If we're actually using commit prefixes, it looks like "plugins" is commonly used for this file.

**Comment by prgmitchell** [comment]
> If we're actually using commit prefixes, it looks like "plugins" is commonly used for this file.

Thanks for pointing this out, I forgot I had started using prefixes here with my last plugins PR. I have updated the commit titles to include the `plugins` prefix.

**Review by RytoEX — APPROVED** [review]
Seems fine.

**Pull request merged**
